# Generated by Django 3.2.6 on 2021-08-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Nome do contato.', max_length=50, unique=True)),
                ('telefone', models.CharField(help_text='Telefone.', max_length=20, unique=True)),
                ('celular', models.CharField(help_text='Celular.', max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Contatos',
                'db_table': 'tab_contato',
                'managed': True,
            },
        ),
    ]
